//curl http://localhost:8000

//curl http://localhost:8000/hello-world

//curl -X PEEK http://localhost:8000/secret

//curl -X PEEK http://localhost:8000/notsecret

//curl "http://localhost:8000?name=Harry"

curl "http://localhost:8000?operation=product&number1=2&number2=4"