//curl http://localhost:8000

//curl http://localhost:8000/hello-world

//curl -X PEEK http://localhost:8000/secret

//curl -X PEEK http://localhost:8000/notsecret

//curl "http://localhost:8000?name=Harry"

//curl "http://localhost:8000?operation=product&number1=2&number2=4"

//curl -X CAT http://localhost:8000/secrets

//curl http://localhost:8000?operation=difference&number1=2&number2=2

//curl http://localhost:8000/congrats?heroOfTheDay=kk

//curl -X DIDNOT http://localhost:8000/lol

curl -X POST http://localhost:8000/feedbacks/1

curl -X POST http://localhost:8000/feedbacks/1

curl http://localhost:8000